services:
    user.form.registration:
        class: UserBundle\Form\RegistrationFormType
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
