<?php

namespace AlbumBundle\Repository;
use Symfony\Component\HttpFoundation\Request;


/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLatest($limit, $offset)
    {
        $queryBuilder = $this->createQueryBuilder('album');

        $queryBuilder->orderBy('album.id', 'DESC')
            ->setFirstResult($offset)
            ->setMaxResults($limit);

        $query = $queryBuilder->getQuery();

        return $query->getResult();
    }

    public function search(AlbumRepository $repository, Request $request)
    {
        $q = $request->query->get('q');
        $albums = $repository->findAllWithSearch($q);
        return $albums;
    }

    public function findAllWithSearch(?string $term)
    {
        $qb = $this->createQueryBuilder('c');

        if ($term) {
            $qb->andWhere('c.title LIKE :term or c.author LIKE :term')
                ->setParameter('term', '%' . $term . '%');
        }

        return $qb
            ->orderBy('c.id', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
